### PR TITLE
shutter.py

### PR DESCRIPTION
**Pull request by jmsojo**
Open and close functions of the shutter renamed to avoid overlapping with the close function of the instrument (that closes the serial connection).

### CODE REVIEW

**Comment by roesel** [comment]
Thank you very much for the PR. In order to clarify: Did you actually run into a situation, where in an attempt to open/close the shutter, you entirely close the serial connection? Or was the renaming motivated by lowering confusion/increasing clarity when reading the code? 

I am mainly asking because I really appreciate the current form of simply running shutter.close() if "shutter" is an existing object. If the naming causes actual real conflicts, I would probably try to find a way to prevent them without renaming the close() method of the Shutter object.

**Comment by jmsojo** [comment]
I haven't tested yet this device as I don't physically have it (only linear stage tested so far). The PR is motivated for lowering confusion. However, it's clear that the shutter.close() function will only work either for moving the shutter or closing the connection, but not for both. One of them will remain inaccessible. Another option is to change the name of close() to close_connection() for the case of the serial, but that implies changing it everywhere else.

**Comment by roesel** [comment]
You are absolutely correct, thanks for that. I didn't realize the conflict was there. 

I fully agree with you that the conflict should be remedied, but the second solution you propose (renaming Controller.close() to Controller.close_connection() ) makes way more sense to me, since the Shutter.open() and Shutter.close() are very nicely descriptive of the physical object, and Controller.close() does not actually make much sense from a physical point of view. Therefore, I think fixing it this way is worth the introduction of a breaking change (especially given how easy it is to fix in the code of the grand total of 5 people who use this library and actually explicitly close their connections 😊). 

If you have the time and feel like implementing this, feel free to do so. Otherwise, I will make this change myself when I find the time. Thank you again for spotting this and filing the PR, I really appreciate it ❤️.

**Comment by roesel** [comment]
This issue is now resolved by commit c1b3cab4316ae4c2fa284b1b4f8e3fb68e5035f0. I renamed the .close() function of the Controller object to .close_connection() and tested with hardware that this doesn't break anything. 

I am sorry it took me such a long time considering how simple the fix was.

Thank you very much again! I am closing this PR for now, feel free to file more in the future. Cheers!

**Pull request closed without merging**
